<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ایجاد، تغییر شکل و برش آرایه‌ها
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این تمرین، ابتدا تعدادی آرایه ایجاد می‌کنیم. سپس ابعاد آنها را تغییر می‌دهیم و آرایه‌های جدیدی می‌سازیم. در آخر با استفاده از ویژگی <code>slicing</code> نامپای، قسمتی از آرایه‌ها را برش می‌دهیم. برای گرفتن نمره کامل این سوال، باید همه متغیر‌ها را درست به دست آورید.
</font>
</p>

In [1]:
import numpy as np
import math

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول: ساخت آرایه‌ها
</font>
</h2>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یک آرایه یک بعدی نامپای به نام <code>a</code>  بسازید که اعداد ۱ تا ۶۴ در آن ذخیره شده باشد. خود ۱ و ۶۴ هم جزو اعداد هستند.
</font>
</p>

In [2]:
a = np.arange(1, 65)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    با کمک گرفتن از توابع عمومی نامپای، آرایه <code>b</code> را ایجاد کنید که سینوس مقادیر ذخیره شده در آرایه <code>a</code> می‌باشد.</font>
</p>

In [3]:
b = np.array([math.sin(i) for i in a])
print(b)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836
 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388 -0.98803162
 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267 -0.99177885
 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267 -0.91652155
 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312 -0.76825466
 -0.95375265 -0.26237485  0.67022918  0.98662759  0.39592515 -0.55878905
 -0.99975517 -0.521551    0.43616476  0.99287265  0.63673801 -0.30481062
 -0.96611777 -0.7391807   0.1673557   0.92002604]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یک آرایه یک بعدی نامپای به نام <code>c</code> بسازید که شامل ۳۰ عدد بین ۱ و ۱۰۰ (شامل خود ۱ و ۱۰۰) با فاصله‌ی برابر باشد، نوع داده را برابر عدد حقیقی ۱۶ بیتی <code>float16</code>  قرار دهید.
</font>
<br>
<font face="vazir" size=3 color="green">
    <b>راهنمایی:</b>
</font>
<font face="vazir" size=3>
    بدین منظور می‌توانید از تابع <a href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html"><code>linspace</code></a> کتابخانه‌ی نامپای بهره ببرید. کافیست اعداد شروع و پایان بازه و همچنین تعداد موردنظر خود را برای این تابع مشخص کنید، تا به تولید آن تعداد عدد در بازه‌ی موردنظر شما و با فاصله‌های برابر بپردازد.
</font>
</p>


In [4]:
c = np.linspace(1, 100, 30, dtype=np.float16)
print(c)


[  1.      4.414   7.83   11.24   14.66   18.06   21.48   24.89   28.31
  31.72   35.12   38.56   41.97   45.38   48.78   52.22   55.62   59.03
  62.44   65.9    69.25   72.7    76.1    79.5    82.94   86.4    89.75
  93.2    96.56  100.   ]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یک آرایه‌ی یک بعدی نامپای به نام <code>d</code> بسازید که اولین عدد آن ۱۲۵ و آخرین عدد آن ۱ باشد. یعنی اعداد از ۱۲۵ تا ۱ یکی یکی کم شوند.
</font>
</p>


In [5]:
d = np.arange(125, 0, -1)
print(d)

[125 124 123 122 121 120 119 118 117 116 115 114 113 112 111 110 109 108
 107 106 105 104 103 102 101 100  99  98  97  96  95  94  93  92  91  90
  89  88  87  86  85  84  83  82  81  80  79  78  77  76  75  74  73  72
  71  70  69  68  67  66  65  64  63  62  61  60  59  58  57  56  55  54
  53  52  51  50  49  48  47  46  45  44  43  42  41  40  39  38  37  36
  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21  20  19  18
  17  16  15  14  13  12  11  10   9   8   7   6   5   4   3   2   1]


<h2 align=right style="direction:rtl;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم: بازآرایی (reshape) </font>
</h2>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در این بخش، آرایه‌های <code>c</code> و <code>d</code> که در بخش قبل ساختید را به آرایه‌هایی دو بعدی و سه بعدی تبدیل می‌کنید. برای این‌کار نیاز است از تابع <code>reshape</code> استفاده کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ابتدا آرایه‌ی <code>c</code> را به آرایه‌ای دو بعدی با اندازه ۵ در محور اول و اندازه ۶ در محور دوم تبدیل کنید و در متغیر <code>e</code> ذخیره کنید.
</font>
<br>
<font face="vazir" size=3 color="#0099cc">
    <b>نکته:</b>
</font>
<font face="vazir" size=3>
توجه داشته باید که در تمام تصاویر این تمرین هر مکعب به معنای یک عنصر (یک مقدار از آرایه) است.
</font>
</p>


<center>
<div style="max-width: 100%">
<img src="e_preview.jpg">
</div>
</center>

In [6]:
e = np.array(c)
e = e.reshape(5, 6)
print(e)

[[  1.      4.414   7.83   11.24   14.66   18.06 ]
 [ 21.48   24.89   28.31   31.72   35.12   38.56 ]
 [ 41.97   45.38   48.78   52.22   55.62   59.03 ]
 [ 62.44   65.9    69.25   72.7    76.1    79.5  ]
 [ 82.94   86.4    89.75   93.2    96.56  100.   ]]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اکنون آرایه‌ی <code>d</code> را به آرایه‌ای سه بعدی با اندازه‌ی ۵ در هر سه محور تبدیل کنید و در متغیر <code>f</code> ذخیره کنید.</font>
</p>

<center>
<div style="max-width: 600px">
<img src="f_preview.jpg">
</div>
</center>


In [7]:
f = np.array(d)
f = f.reshape(5, 5, 5)
print(f)

[[[125 124 123 122 121]
  [120 119 118 117 116]
  [115 114 113 112 111]
  [110 109 108 107 106]
  [105 104 103 102 101]]

 [[100  99  98  97  96]
  [ 95  94  93  92  91]
  [ 90  89  88  87  86]
  [ 85  84  83  82  81]
  [ 80  79  78  77  76]]

 [[ 75  74  73  72  71]
  [ 70  69  68  67  66]
  [ 65  64  63  62  61]
  [ 60  59  58  57  56]
  [ 55  54  53  52  51]]

 [[ 50  49  48  47  46]
  [ 45  44  43  42  41]
  [ 40  39  38  37  36]
  [ 35  34  33  32  31]
  [ 30  29  28  27  26]]

 [[ 25  24  23  22  21]
  [ 20  19  18  17  16]
  [ 15  14  13  12  11]
  [ 10   9   8   7   6]
  [  5   4   3   2   1]]]


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
(slice) بخش سوم: برش
</font>
</h2>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    آرایه‌ی دو‌بعدی <code>e</code> را مطابق شکل زیر برش دهید و در متغیر <code>g</code> ذخیره کنید. یعنی در متغیر <code>g</code> تنها باید مواردی که در ماتریس زیر پررنگ شده‌اند را خروجی دهید، یعنی ماتریس خروجی شما باید دارای ابعاد ۳ در ۳ باشد.</p>

<center>
<div style="max-width: 600px">
<img src="g_preview.jpg">
</div>
</center>

In [8]:
g = e[0:5:2, 1:6:2]

print(g)

[[  4.414  11.24   18.06 ]
 [ 45.38   52.22   59.03 ]
 [ 86.4    93.2   100.   ]]


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    آرایه‌ی سه‌بعدی <code>f</code> را مطابق شکل زیر برش دهید و در متغیر <code>h</code> بریزید. آرایه‌ی خروجی، سه‌بعدی و دارای ۸ عدد خواهد بود (هرکدام از مکعب‌ها یک عنصر از آرایه هستند و مجموعاً ۸ مکعب پررنگ نشان داده شده است).
</p>

<center>
<div style="max-width: 600px">
<img src="h_preview.jpg">
</div>
</center>

In [9]:
h = f[-2:, -2:, :2]
print(h)

[[[35 34]
  [30 29]]

 [[10  9]
  [ 5  4]]]


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [10]:
import zlib
import zipfile

np.savez("answers.npz", a = a, b = b, c = c, d = d, e = e, f = f, g = g, h = h)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["answers.npz", "create_reshape_and_slice.ipynb"]
compress(file_names)

OSError: [Errno 9] Bad file descriptor